site_name: Bước nhỏ
site_url: https://sitename.example
theme:
  name: material
  custom_dir: overrides
  font:
    text: Merriweather
    code: Red Hat Mono
  palette:
    primary: brown
    accent: amber
  features:
    - navigation.footer
    - navigation.expand  # Tự động mở rộng các mục menu
    - navigation.indexes # Cho phép click vào mục cha
    - navigation.tracking # Tự động cuộn đến vị trí đang xem

    
extra_css:
  - stylesheets/layout.css