site_name: Bước nhỏ
site_url: https://sitename.example
theme:
  name: material
  custom_dir: overrides
  font:
    text: Merriweather
    code: Red Hat Mono
  palette:
    primary: brown
    accent: amber
  features:
    - navigation.footer
    
extra_css:
  - stylesheets/layout.css